'use strict';var _createClass=(function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if('value' in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor}})();function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function')}}(function(){var Sand=window.Sand=window.Sand||{};var su=Sand.Utils;Sand.Events=Sand.Events||{};var colorChangeEvt=Sand.Events.ColorChange=new Event('colorchange',{'bubbles':true});var scp=Sand.ColorPicker=(function(){function _class(){var width=arguments.length<=0||arguments[0]===undefined?500:arguments[0];var height=arguments.length<=1||arguments[1]===undefined?500:arguments[1];_classCallCheck(this,_class);this._width=width;this._height=height/6;this._container=document.createElement('div');this._container.classList.add('color-picker');this.currHue=0;this.currSat=100;this.currLit=50;this._updateColor();this.createHueSlider();this.createValueField()}_createClass(_class,[{key:'_updateColor',value:function _updateColor(){this._color=new su.Color(this.currHue,this.currSat,this.currLit);this.triggerEvent()}},{key:'render',value:function render(){return this}},{key:'el',value:function el(){return this._container}},{key:'createHueSlider',value:function createHueSlider(){var _this=this;this._hs=document.createElement('canvas');this._hs.setAttribute('width',this._width);this._hs.setAttribute('height',this._height);this._container.appendChild(this._hs);this._hsctx=this._hs.getContext('2d');this.updateHueField();var mDown=false,oldOffset=0;su.addDragEvents(this._hs,{'move':function move(e){if(!mDown)return;var cHue=_this.offset=e.offsetX/_this._width*360; // let cHue = (e.offsetX / this._width * 360);
// this.offset = oldOffset + cHue;
_this.updateHueField();_this.updateValueField(cHue,5)},'end':function end(e){if(oldOffset==_this.offset){_this.offset+=e.offsetX/_this._width*360}_this.pickHue(e);mDown=false},'start':function start(e){mDown=true;oldOffset=_this.offset}}); // this._hs.addEventListener('mousemove', e => {
//   if (!mDown) return;
//   let cHue = this.offset = (e.offsetX / this._width * 360);
//   // let cHue = (e.offsetX / this._width * 360);
//   // this.offset = oldOffset + cHue;
//   this.updateHueField();
//   this.updateValueField(cHue, 5);
// });
// this._hs.addEventListener('mouseup', e => {
//   if (oldOffset == this.offset) {
//     this.offset += (e.offsetX / this._width * 360);
//   }
//   this.pickHue(e);
//   mDown = false;
// });
// this._hs.addEventListener('mousedown', e => {
//   mDown = true;
//   oldOffset = this.offset;
// });
}},{key:'updateHueField',value:function updateHueField(){var currColor;this.offset=this.offset||1;var unit=this._width/360;for(var h=0;h<360;h++){currColor=new su.Color(h+this.offset,this.currSat,this.currLit);this._hsctx.fillStyle=currColor.toString();this._hsctx.fillRect(unit*h,0,unit+1,50)}}},{key:'triggerEvent',value:function triggerEvent(){this._container.dispatchEvent(colorChangeEvt)}},{key:'pickHue',value:function pickHue(e){this.currHue=this.offset; // this.currHue = ((e.offsetX / this._width * 360) + this.offset) % 360;
// this.offset = this.currHue;
this._color.hue(this.currHue);this.triggerEvent();this.updateValueField(this.currHue);this.updateHueField()}},{key:'createValueField',value:function createValueField(){this._vf=document.createElement('canvas');this._vf.setAttribute('width',this._width);this._vf.setAttribute('height',this._height*5);this._container.appendChild(this._vf);this._vfctx=this._vf.getContext('2d');this.updateValueField();this._vf.addEventListener('click',this.pickValue.bind(this))}},{key:'updateValueField',value:function updateValueField(){var hue=arguments.length<=0||arguments[0]===undefined?null:arguments[0];var res=arguments.length<=1||arguments[1]===undefined?100:arguments[1];var unitX=this._width/res;var unitY=this._vfctx.canvas.height/res;var cHue=hue===null?this.currHue:hue;var currColor=new su.Color(cHue,0,0);for(var s=0;s<=100;s+=100/res){for(var l=0;l<=100;l+=100/res){currColor.saturation(s).lightness((s+l)/2);this._vfctx.fillStyle=currColor.toString();this._vfctx.fillRect(unitX*s/(100/res),unitY*l/(100/res),unitX+1,unitY+1)}}}},{key:'pickValue',value:function pickValue(e){this.currSat=e.offsetX/this._vf.clientWidth*100;this.currLit=(e.offsetY/this._vf.clientHeight+e.offsetX/this._width)*50;this._updateColor();this.updateHueField()}},{key:'getColor',value:function getColor(){return this._color}}]);return _class})()})();